version: '3.4'

services:
  distributedlog.master:
    image: ${DOCKER_REGISTRY-}distributedlogmaster
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: DistributedLog.Master/Dockerfile
    ports:
      - "5000:80"

  distributedlog.replica1:
    image: ${DOCKER_REGISTRY-}distributedlogreplica
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: DistributedLog.Replica/Dockerfile
    ports:
      - "5001:80"

  distributedlog.replica2:
    image: ${DOCKER_REGISTRY-}distributedlogreplica
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: DistributedLog.Replica/Dockerfile
    ports:
      - "5002:80"